const chaveamento = [
    {
        id: 73,
        fase: "rodada32",
        mandante: "2A",
        visitante: "2B",
        data: "28 de junho",
        dia: "domingo",
        horario: "",
        estadio: "SoFi",
        cidade: "Los Angeles",
        pais: "Estados Unidos",
    },
    {
        id: 74,
        fase: "rodada32",
        mandante: "1E",
        visitante: "3ABCDF",
        data: "29 de junho",
        dia: "segunda-feira",
        horario: "",
        estadio: "Gillette",
        cidade: "Boston",
        pais: "Estados Unidos",
    },
    {
        id: 75,
        fase: "rodada32",
        mandante: "1F",
        visitante: "2C",
        data: "29 de junho",
        dia: "segunda-feira",
        horario: "",
        estadio: "BBVA",
        cidade: "Monterrey",
        pais: "México",
    },
    {
        id: 76,
        fase: "rodada32",
        mandante: "1C",
        visitante: "2F",
        data: "29 de junho",
        dia: "segunda-feira",
        horario: "",
        estadio: "NGR",
        cidade: "Houston",
        pais: "Estados Unidos",
    },
    {
        id: 77,
        fase: "rodada32",
        mandante: "1I",
        visitante: "3CDFGH",
        data: "30 de junho",
        dia: "terça-feira",
        horario: "",
        estadio: "Met Life",
        cidade: "Nova York",
        pais: "Estados Unidos",
    },
    {
        id: 78,
        fase: "rodada32",
        mandante: "2E",
        visitante: "2I",
        data: "30 de junho",
        dia: "terça-feira",
        horario: "",
        estadio: "AT&T",
        cidade: "Dallas",
        pais: "Estados Unidos",
    },
    {
        id: 79,
        fase: "rodada32",
        mandante: "1A",
        visitante: "3CEFHI",
        data: "30 de junho",
        dia: "terça-feira",
        horario: "",
        estadio: "Azteca",
        cidade: "Cidade do México",
        pais: "México",
    },
    {
        id: 80,
        fase: "rodada32",
        mandante: "1L",
        visitante: "3EHIJK",
        data: "1º de julho",
        dia: "quarta-feira",
        horario: "",
        estadio: "Mercedes-Benz",
        cidade: "Atlanta",
        pais: "Estados Unidos",
    },
    {
        id: 81,
        fase: "rodada32",
        mandante: "1D",
        visitante: "3BEFIJ",
        data: "1º de julho",
        dia: "quarta-feira",
        horario: "",
        estadio: "Levi's",
        cidade: "San Francisco",
        pais: "Estados Unidos",
    },
    {
        id: 82,
        fase: "rodada32",
        mandante: "1G",
        visitante: "3AEHIJ",
        data: "1º de julho",
        dia: "quarta-feira",
        horario: "",
        estadio: "Lumen Field",
        cidade: "Seattle",
        pais: "Estados Unidos",
    },
    {
        id: 83,
        fase: "rodada32",
        mandante: "2K",
        visitante: "2L",
        data: "2 de julho",
        dia: "quinta-feira",
        horario: "",
        estadio: "BMO Field",
        cidade: "Toronto",
        pais: "Canadá",
    },
    {
        id: 84,
        fase: "rodada32",
        mandante: "1H",
        visitante: "2J",
        data: "2 de julho",
        dia: "quinta-feira",
        horario: "",
        estadio: "SoFi",
        cidade: "Los Angeles",
        pais: "Estados Unidos",
    },
    {
        id: 85,
        fase: "rodada32",
        mandante: "1B",
        visitante: "3EFGIJ",
        data: "2 de julho",
        dia: "quinta-feira",
        horario: "",
        estadio: "BC Place",
        cidade: "Vancouver",
        pais: "Canadá",
    },
    {
        id: 86,
        fase: "rodada32",
        mandante: "1J",
        visitante: "2H",
        data: "3 de julho",
        dia: "sexta-feira",
        horario: "",
        estadio: "Hard Rock",
        cidade: "Miami",
        pais: "Estados Unidos",
    },
    {
        id: 87,
        fase: "rodada32",
        mandante: "1K",
        visitante: "3DEIJL",
        data: "3 de julho",
        dia: "sexta-feira",
        horario: "",
        estadio: "GEHA Field at Arrowhead",
        cidade: "Kansas City",
        pais: "Estados Unidos",
    },
    {
        id: 88,
        fase: "rodada32",
        mandante: "2D",
        visitante: "2G",
        data: "3 de julho",
        dia: "sexta-feira",
        horario: "",
        estadio: "AT&T",
        cidade: "Dallas",
        pais: "Estados Unidos",
    },
    {
        id: 89,
        fase: "oitavas",
        mandante: "V74",
        visitante: "V77",
        data: "4 de julho",
        dia: "sábado",
        horario: "",
        estadio: "Lincoln Financial Field",
        cidade: "Filadélfia",
        pais: "Estados Unidos",
    },
    {
        id: 90,
        fase: "oitavas",
        mandante: "V73",
        visitante: "V75",
        data: "4 de julho",
        dia: "sábado",
        horario: "",
        estadio: "NGR",
        cidade: "Houston",
        pais: "Estados Unidos",
    },
    {
        id: 91,
        fase: "oitavas",
        mandante: "V76",
        visitante: "V78",
        data: "5 de julho",
        dia: "domingo",
        horario: "",
        estadio: "Met Life",
        cidade: "Nova York",
        pais: "Estados Unidos",
    },
    {
        id: 92,
        fase: "oitavas",
        mandante: "V79",
        visitante: "V80",
        data: "5 de julho",
        dia: "domingo",
        horario: "",
        estadio: "Azteca",
        cidade: "Cidade do México",
        pais: "México",
    },
    {
        id: 93,
        fase: "oitavas",
        mandante: "V83",
        visitante: "V84",
        data: "6 de julho",
        dia: "segunda-feira",
        horario: "",
        estadio: "AT&T",
        cidade: "Dallas",
        pais: "Estados Unidos",
    },
    {
        id: 94,
        fase: "oitavas",
        mandante: "V81",
        visitante: "V82",
        data: "6 de julho",
        dia: "segunda-feira",
        horario: "",
        estadio: "Lumen Field",
        cidade: "Seattle",
        pais: "Estados Unidos",
    },
    {
        id: 95,
        fase: "oitavas",
        mandante: "V86",
        visitante: "V88",
        data: "7 de julho",
        dia: "terça-feira",
        horario: "",
        estadio: "Mercedes-Benz",
        cidade: "Atlanta",
        pais: "Estados Unidos",
    },
    {
        id: 96,
        fase: "oitavas",
        mandante: "V85",
        visitante: "V87",
        data: "7 de julho",
        dia: "terça-feira",
        horario: "",
        estadio: "BC Place",
        cidade: "Vancouver",
        pais: "Canadá",
    },
    {
        id: 97,
        fase: "quartas",
        mandante: "V89",
        visitante: "V90",
        data: "9 de julho",
        dia: "quinta-feira",
        horario: "",
        estadio: "Gillette",
        cidade: "Boston",
        pais: "Estados Unidos",
    },
    {
        id: 98,
        fase: "quartas",
        mandante: "V93",
        visitante: "V94",
        data: "10 de julho",
        dia: "sexta-feira",
        horario: "",
        estadio: "SoFi",
        cidade: "Los Angeles",
        pais: "Estados Unidos",
    },
    {
        id: 99,
        fase: "quartas",
        mandante: "V91",
        visitante: "V92",
        data: "11 de julho",
        dia: "sábado",
        horario: "",
        estadio: "Hard Rock",
        cidade: "Miami",
        pais: "Estados Unidos",
    },
    {
        id: 100,
        fase: "quartas",
        mandante: "V95",
        visitante: "V96",
        data: "11 de julho",
        dia: "sábado",
        horario: "",
        estadio: "GEHA Field at Arrowhead",
        cidade: "Kansas City",
        pais: "Estados Unidos",
    },
    {
        id: 101,
        fase: "semi",
        mandante: "V97",
        visitante: "V98",
        data: "14 de julho",
        dia: "terça-feira",
        horario: "",
        estadio: "AT&T",
        cidade: "Dallas",
        pais: "Estados Unidos",
    }, // linha 349
    {
        id: 102,
        fase: "semi",
        mandante: "V99",
        visitante: "V100",
        data: "15 de julho",
        dia: "quarta-feira",
        horario: "",
        estadio: "Mercedes-Benz",
        cidade: "Atlanta",
        pais: "Estados Unidos",
    },
    {
        id: 103,
        fase: "terceiro",
        mandante: "P101", // linha365
        visitante: "P102",
        data: "18 de julho",
        dia: "sábado",
        horario: "",
        estadio: "Hard Rock",
        cidade: "Miami",
        pais: "Estados Unidos",
    },
    {
        id: 104,
        fase: "final",
        mandante: "V101",
        visitante: "V102",
        data: "19 de julho",
        dia: "domingo",
        horario: "",
        estadio: "Met Life",
        cidade: "Nova York",
        pais: "Estados Unidos",
    }
];

function preencherTime(elemento, nomeOuCodigo) {
    const selecao = classificados.find(s => s.selecao === nomeOuCodigo);

    if (selecao) {
        elemento.querySelector("img").src = "bandeiras/" + selecao.bandeira;
        elemento.querySelector("img").alt = selecao.selecao;
        elemento.querySelector(".nome").textContent = selecao.sigla;
    } else {
        elemento.querySelector("img").src = "bandeiras/onu.png";
        elemento.querySelector("img").alt = nomeOuCodigo;
        elemento.querySelector(".nome").textContent = nomeOuCodigo;
    }
}

chaveamento.forEach(jogo => {
    const jogoDiv = document.querySelector(`[data-id='${jogo.id}']`);
    if (!jogoDiv) return;

    const times = jogoDiv.querySelectorAll(".time, .time-oitavas, .time-quartas, .time-semi, .finalista");

    preencherTime(times[0], jogo.mandante);
    preencherTime(times[1], jogo.visitante);
});

